### PR TITLE
v2.1.0

### PR DESCRIPTION
**Pull request by vemv**
Delivers: https://github.com/nedap/components.assets/pull/8, https://github.com/nedap/components.assets/commit/105778ad7973f61da38860ce986be1a31cf628a2, 639c052e955fcc17c72a75d52dd78fde1322574a

## Release checklist (author)

* [x] All PRs / relevant commits since the previous release are listed in this PR's description 
* [x] The new proposed version follows semver 
* [x] The build passes
* [x] New features are (briefly) reflected in the README

## Release checklist (reviewer)

* [ ] All PRs / relevant commits since the previous release are listed in this PR's description 
* [ ] The new proposed version follows semver 
* [ ] New features are (briefly) reflected in the README

### CODE REVIEW

**Comment by vemv** [comment]
Hmm, hang for a while, `com.nedap.staffing-solutions/utils.io` also needs OSSing

**Comment by thumbnail** [comment]
Should we remove our privatr repositories from project.clj?

**Comment by vemv** [comment]
Good q! Answered here: https://github.com/nedap/utils.collections/issues/11#issuecomment-602639860

**Comment by vemv** [comment]
Released - thanks!

**Pull request merged**
